# <center>Laboratorio 3</center>

#### ***Nombre***: Jose Eduardo Calderon Lopez
#### ***Carnet***: 14001764

<br>
<hr>
<br>

# Parte 1: Numpy

In [64]:
import numpy as np

### 1. Ejercicio

In [6]:
arrayBools = np.random.choice([True, False], size=1000)

print("¿Cuál es el tamaño en bytes de un array de 1000 elementos de tipo booleano?")
print(f"Respuesta: {arrayBools.nbytes}")

¿Cuál es el tamaño en bytes de un array de 1000 elementos de tipo booleano?
Respuesta: 1000


### 2. Ejercicio

In [17]:
pares = np.arange(100,0,-2)

print(pares[40:])

[20 18 16 14 12 10  8  6  4  2]


### 3. Ejercicio

In [50]:
array = np.array([[2,4,5,6],[0,3,7,4],[8,8,5,2],[1,5,6,1]])

subarray1 = array[1]
subarray2 = array[[0,2],:][:,[0,2]]

print(subarray1)
print("")
print(subarray2)

[0 3 7 4]

[[2 5]
 [8 5]]


### 4. Ejercicio

In [48]:
a = np.array([1, 4, 2, 7])
b = np.array([1, 3, 2, 9])

media = np.mean(a-b)

print(f"Media aritmética de a-b:\n{media}")

Media aritmética de a-b:
-0.25


### 5. Ejercicio

In [75]:
coordenadas = np.array([[1.33,4.5],[30.0,10.7],[70.2,0.5]])

coordenadas = np.append(coordenadas, [[37.1,-3.6]], axis=0)

print(coordenadas)

[[ 1.33  4.5 ]
 [30.   10.7 ]
 [70.2   0.5 ]
 [37.1  -3.6 ]]


### 6. Ejercicio

In [87]:
transpose = np.transpose(coordenadas)

transpose = np.append(transpose, [[35.8],[12.0]], axis=1)

print(transpose)

[[ 1.33 30.   70.2  37.1  35.8 ]
 [ 4.5  10.7   0.5  -3.6  12.  ]]


# Parte 2: Exploración y Minería de Datos

In [88]:
import pandas as pd

In [214]:
datos = pd.read_csv('NucleosPoblacion.csv')

datos.head()

FID  OBJECTID     Texto  Poblacion  CodMun Municipio  CodProvin  \
0    0         1   Agüimes    29431.0   35002   Agüimes         35   
1    1         2   Antigua    10458.0   35003   Antigua         35   
2    2         3  Arrecife    58156.0   35004  Arrecife         35   
3    3         4    Arucas    36745.0   35006    Arucas         35   
4    4         5    Gáldar    24473.0   35009    Gáldar         35   

    Provincia          X          Y  
0  Las Palmas -15.446012  27.900542  
1  Las Palmas -14.013301  28.418966  
2  Las Palmas -13.551451  28.960649  
3  Las Palmas -15.521512  28.117496  
4  Las Palmas -15.654111  28.143873

### 1. Ejercicio

In [215]:
municipios = datos[datos['Poblacion'] > 100000]

# display(municipios)

print(f"Municipios con más de 100,000 habitantes\nRespuesta: {len(municipios)}")

Municipios con más de 100,000 habitantes
Respuesta: 62


### 2. Ejercicio

In [201]:
ordenPorCiudad = datos.sort_values(by='Poblacion')
segundaCiudadMasPoblada = ordenPorCiudad.iloc[-2]['Municipio']

print("¿Cuál es la segunda ciudad más poblada?")
print("Respuesta: ",segundaCiudadMasPoblada)

¿Cuál es la segunda ciudad más poblada?
Respuesta:  Barcelona


In [203]:
ordenPorCiudad['Orden'] = range(1,len(ordenPorCiudad)+1)
datosGranada = ordenPorCiudad[ordenPorCiudad['Municipio'] == 'Granada']
posicionGranada = datosGranada['Orden'].iloc[0]

print("¿Qué posición ocupa Granada en el ranking de las ciudades más pobladas?")
print(f"Respuesta: {posicionGranada}")

¿Qué posición ocupa Granada en el ranking de las ciudades más pobladas?
Respuesta: 835


### 3. Ejercicio

In [218]:
masDe5000Extremadura = datos[(datos['Provincia'] == 'Extremadura') & (datos['Poblacion'] > 5000)]
cantidad = len(masDe5000Extremadura)

print("¿Cuántos municipios de Extremadura tienen más de 5000 habitantes?")
print(f"Respuesta: {cantidad}")

¿Cuántos municipios de Extremadura tienen más de 5000 habitantes?
Respuesta: 0
