# <center>Laboratorio 3</center>

#### ***Nombre***: Jose Eduardo Calderon Lopez
#### ***Carnet***: 14001764

<br>
<hr>
<br>

# Parte 1: Numpy

In [64]:
import numpy as np

### 1. Ejercicio

In [6]:
arrayBools = np.random.choice([True, False], size=1000)

print("¿Cuál es el tamaño en bytes de un array de 1000 elementos de tipo booleano?")
print(f"Respuesta: {arrayBools.nbytes}")

¿Cuál es el tamaño en bytes de un array de 1000 elementos de tipo booleano?
Respuesta: 1000


### 2. Ejercicio

In [17]:
pares = np.arange(100,0,-2)

print(pares[40:])

[20 18 16 14 12 10  8  6  4  2]


### 3. Ejercicio

In [50]:
array = np.array([[2,4,5,6],[0,3,7,4],[8,8,5,2],[1,5,6,1]])

subarray1 = array[1]
subarray2 = array[[0,2],:][:,[0,2]]

print(subarray1)
print("")
print(subarray2)

[0 3 7 4]

[[2 5]
 [8 5]]


### 4. Ejercicio

In [48]:
a = np.array([1, 4, 2, 7])
b = np.array([1, 3, 2, 9])

media = np.mean(a-b)

print(f"Media aritmética de a-b:\n{media}")

Media aritmética de a-b:
-0.25


### 5. Ejercicio

In [75]:
coordenadas = np.array([[1.33,4.5],[30.0,10.7],[70.2,0.5]])

coordenadas = np.append(coordenadas, [[37.1,-3.6]], axis=0)

print(coordenadas)

[[ 1.33  4.5 ]
 [30.   10.7 ]
 [70.2   0.5 ]
 [37.1  -3.6 ]]


### 6. Ejercicio

In [87]:
transpose = np.transpose(coordenadas)

transpose = np.append(transpose, [[35.8],[12.0]], axis=1)

print(transpose)

[[ 1.33 30.   70.2  37.1  35.8 ]
 [ 4.5  10.7   0.5  -3.6  12.  ]]


# Parte 2: Exploración y Minería de Datos